# Generated by Django 4.2.2 on 2023-06-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('semester', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('prof_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('subject_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('midterm', models.FileField(blank=True, default='', null=True, upload_to='midterm/')),
                ('final_exam', models.FileField(blank=True, default='', null=True, upload_to='final_exam/')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='majors_app.majors')),
            ],
        ),
    ]
